import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import { DayOfWeek, Schedule } from '../../../generated/prisma';

@Injectable()
export class ScheduleRepository {
  constructor(private readonly prisma: PrismaService) {}

  async findConflict(
    courseCode: string,
    sessionId: string,
    excludeId?: string,
  ): Promise<Schedule | null> {
    return this.prisma.schedule.findFirst({
      where: {
        courseCode,
        sessionId,
        ...(excludeId && { id: { not: excludeId } }),
      },
    });
  }

  async getScheduleStats(): Promise<{
    totalSchedules: number;
    schedulesByDay: Record<DayOfWeek, number>;
    autoGenerated: number;
    manualOverrides: number;
  }> {
    const [total, autoGenerated, manualOverrides] = await Promise.all([
      this.prisma.schedule.count(),
      this.prisma.schedule.count({ where: { isAutoGenerated: true, isManualOverride: false } }),
      this.prisma.schedule.count({ where: { isManualOverride: true } }),
    ]);

    const schedulesByDay = {} as Record<DayOfWeek, number>;
    for (const day of Object.values(DayOfWeek)) {
      schedulesByDay[day] = await this.prisma.schedule.count({ where: { dayOfWeek: day } });
    }

    return { totalSchedules: total, schedulesByDay, autoGenerated, manualOverrides };
  }
}
