import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import { DayOfWeek, Schedule } from '../../../generated/prisma';

@Injectable()
export class ScheduleRepository {
  constructor(private readonly prisma: PrismaService) {}

  async findConflict(
    courseCode: string,
    sessionId: string,
    excludeId?: string,
  ): Promise<Schedule | null> {
    return this.prisma.schedule.findFirst({
      where: {
        courseCode,
        sessionId,
        ...(excludeId ? { id: { not: excludeId } } : {}),
      },
    });
  }

  async getScheduleStats(): Promise<{
    totalSchedules: number;
    schedulesByDay: Record<DayOfWeek, number>;
    autoGenerated: number;
    manualOverrides: number;
  }> {
    const [total, autoGenerated, manualOverrides, dayGroups] =
      await Promise.all([
        this.prisma.schedule.count(),
        this.prisma.schedule.count({
          where: { isAutoGenerated: true, isManualOverride: false },
        }),
        this.prisma.schedule.count({ where: { isManualOverride: true } }),
        this.prisma.schedule.groupBy({
          by: ['dayOfWeek'],
          _count: { _all: true },
        }),
      ]);

    const schedulesByDay = Object.fromEntries(
      Object.values(DayOfWeek).map((d) => [d, 0]),
    ) as Record<DayOfWeek, number>;

    for (const row of dayGroups) {
      schedulesByDay[row.dayOfWeek] = row._count._all;
    }

    return {
      totalSchedules: total,
      schedulesByDay,
      autoGenerated,
      manualOverrides,
    };
  }
}
