import {
  Injectable,
  ConflictException,
  NotFoundException,
  BadRequestException,
  ForbiddenException,
  UnprocessableEntityException,
} from '@nestjs/common';
import { PrismaService } from '../database/prisma.service';
import { CreateScheduleDto } from './dto/create-schedule.dto';
import { UpdateScheduleDto } from './dto/update-schedule.dto';
import { ScheduleFilterDto } from './dto/schedule-filter.dto';
import {
  BatchGenerateScheduleResult,
  GenerateScheduleDto,
  GenerateScheduleResult,
} from './dto/generate-schedule.dto';
import { BaseService } from '../../common/services/base.service';
import { ScheduleRepository } from './repositories/schedule.repository';
import {
  SchedulerEngine,
  LockedSlot,
  CourseInput,
  ScheduleAssignment,
} from './scheduler/scheduler.engine';
import {
  College,
  DayOfWeek,
  Level,
  Role,
  Schedule,
} from '../../generated/prisma';
import { PaginatedResult } from '../../common/interfaces/base-service.interface';

@Injectable()
export class SchedulesService extends BaseService<
  Schedule,
  CreateScheduleDto,
  UpdateScheduleDto
> {
  constructor(
    prisma: PrismaService,
    private readonly scheduleRepository: ScheduleRepository,
    private readonly schedulerEngine: SchedulerEngine,
  ) {
    super(prisma, {
      modelName: 'schedule',
      identifierField: 'id',
      includeRelations: {
        course: {
          include: {
            department: true,
            lecturer: {
              select: { id: true, name: true, email: true },
            },
            primaryAliases: {
              include: {
                aliasCourse: {
                  select: { code: true, name: true, departmentCode: true },
                },
              },
            },
            aliasOf: {
              include: {
                primaryCourse: {
                  select: { code: true, name: true, departmentCode: true },
                },
              },
            },
          },
        },
      },
      defaultOrderBy: { dayOfWeek: 'asc' },
    });
  }

  protected async beforeCreate(
    dto: CreateScheduleDto,
  ): Promise<Record<string, any>> {
    const activeSession = await this.prisma.academicSession.findFirst({
      where: { isActive: true },
    });

    if (!activeSession) {
      throw new ConflictException('No active academic session found');
    }

    const course = await this.prisma.course.findUnique({
      where: { code: dto.courseCode },
      select: { semester: true, isGeneral: true, level: true },
    });

    if (!course) {
      throw new NotFoundException(`Course '${dto.courseCode}' not found`);
    }

    this.validateTimeSlot(dto.startTime, dto.endTime, dto.dayOfWeek);

    const existing = await this.scheduleRepository.findConflict(
      dto.courseCode,
      activeSession.id,
    );

    if (existing) {
      throw new ConflictException(
        `Course '${dto.courseCode}' already has a schedule this session. Update the existing one.`,
      );
    }

    if (!course.isGeneral) {
      await this.checkUniversityCourseClash(
        course.level,
        dto.dayOfWeek,
        dto.startTime,
        dto.endTime,
        activeSession.id,
      );
    }

    const isFixed = course.isGeneral ? true : (dto.isFixed ?? false);

    return {
      ...dto,
      sessionId: activeSession.id,
      semester: course.semester,
      isAutoGenerated: false,
      isManualOverride: true,
      isFixed,
    };
  }

  protected async beforeUpdate(
    dto: UpdateScheduleDto,
    identifier: string,
  ): Promise<Record<string, any>> {
    const current = await this.prisma.schedule.findUnique({
      where: { id: identifier },
      include: {
        course: { select: { isGeneral: true, level: true } },
      },
    });

    if (!current) {
      throw new NotFoundException(`Schedule '${identifier}' not found`);
    }

    const resolvedDay = dto.dayOfWeek ?? current.dayOfWeek;
    const resolvedStart = dto.startTime ?? current.startTime;
    const resolvedEnd = dto.endTime ?? current.endTime;

    this.validateTimeSlot(resolvedStart, resolvedEnd, resolvedDay);

    if (!current.course.isGeneral) {
      await this.checkUniversityCourseClash(
        current.course.level,
        resolvedDay,
        resolvedStart,
        resolvedEnd,
        current.sessionId,
        identifier,
      );
    }

    const isFixed = current.course.isGeneral
      ? true
      : (dto.isFixed ?? current.isFixed);

    return {
      ...dto,
      isManualOverride: true,
      isAutoGenerated: false,
      isFixed,
    };
  }

  async findAll(
    query: ScheduleFilterDto = {},
  ): Promise<Schedule[] | PaginatedResult<Schedule>> {
    const where: Record<string, unknown> = {};

    if (query.semester) where.semester = query.semester;

    if (query.sessionId) {
      where.sessionId = query.sessionId;
    } else {
      const activeSession = await this.prisma.academicSession.findFirst({
        where: { isActive: true },
      });

      if (!activeSession) {
        return [] as Schedule[];
      }

      where.sessionId = activeSession.id;
    }

    if (query.courseCode) where.courseCode = query.courseCode;
    if (query.dayOfWeek) where.dayOfWeek = query.dayOfWeek;

    if (query.departmentCode ?? query.level) {
      if (query.departmentCode) {
        const deptCondition: Record<string, unknown> = {
          departmentCode: query.departmentCode,
        };
        const generalCondition: Record<string, unknown> = { isGeneral: true };

        if (query.level) {
          deptCondition.level = query.level;
          generalCondition.level = query.level;
        }

        if (query.programme) {
          deptCondition.code = { startsWith: query.programme };
        }

        where.course = { OR: [deptCondition, generalCondition] };
      } else {
        where.course = { level: query.level };
      }
    } else if (query.programme) {
      where.course = { code: { startsWith: query.programme } };
    }

    if (query.startTime) where.startTime = { gte: query.startTime };
    if (query.endTime) where.endTime = { lte: query.endTime };

    if (query.page !== undefined && query.limit !== undefined) {
      return this.findPaginated(where, query);
    }

    return this.getModel().findMany({
      where,
      include: this.config.includeRelations,
      orderBy: [{ dayOfWeek: 'asc' }, { startTime: 'asc' }],
    }) as Promise<Schedule[]>;
  }

  async generateSchedules(
    dto: GenerateScheduleDto,
    requestingUser: { id: string; role: string; collegeCode?: College },
  ): Promise<GenerateScheduleResult> {
    const session = dto.sessionId
      ? await this.prisma.academicSession.findUnique({
          where: { id: dto.sessionId },
        })
      : await this.prisma.academicSession.findFirst({
          where: { isActive: true },
        });

    if (!session) {
      throw new NotFoundException(
        dto.sessionId
          ? `Session '${dto.sessionId}' not found`
          : 'No active academic session found',
      );
    }

    let departmentCode: string | null = dto.departmentCode ?? null;
    const level: Level | null = dto.level ?? null;
    const programme: string | null = dto.programme ?? null;

    if (requestingUser.role === Role.HOD) {
      const hodUser = await this.prisma.user.findUnique({
        where: { id: requestingUser.id },
        include: { managedDepartment: true },
      });

      if (!hodUser?.managedDepartment) {
        throw new ForbiddenException('HOD must be assigned to a department');
      }

      departmentCode = hodUser.managedDepartment.code;
    }

    const collegeScope = this.resolveCollegeScope(requestingUser);

    const lockedDepartmentCodes =
      await this.resolveLockedDepartmentCodes(departmentCode);

    const departmentalCourseFilter: Record<string, any> = {
      isActive: true,
      semester: dto.semester,
      isGeneral: false,
    };

    if (departmentCode) {
      departmentalCourseFilter.departmentCode = departmentCode;
    } else {
      if (collegeScope) {
        departmentalCourseFilter.department = { college: collegeScope };
      }
      if (lockedDepartmentCodes.length > 0) {
        departmentalCourseFilter.departmentCode = {
          notIn: lockedDepartmentCodes,
        };
      }
    }

    if (level) departmentalCourseFilter.level = level;
    if (programme) departmentalCourseFilter.code = { startsWith: programme };

    const universityCourseFilter: Record<string, any> = {
      isActive: true,
      semester: dto.semester,
      isGeneral: true,
    };
    if (level) universityCourseFilter.level = level;

    const [departmentalCourses, universityCourses] = await Promise.all([
      this.prisma.course.findMany({
        where: departmentalCourseFilter,
        include: { department: true },
      }),
      collegeScope
        ? Promise.resolve([])
        : this.prisma.course.findMany({
            where: universityCourseFilter,
            include: { department: true },
          }),
    ]);

    const allCourses = [...departmentalCourses, ...universityCourses];

    if (allCourses.length === 0) {
      return {
        sessionId: session.id,
        sessionName: session.name,
        semester: dto.semester,
        departmentCode,
        programme,
        level,
        totalCourses: 0,
        scheduledCourses: 0,
        preservedOverrides: 0,
        skippedLockedDepartments: lockedDepartmentCodes.length,
      };
    }

    const allDepartments = await this.prisma.department.findMany({
      where: { isActive: true },
      select: { code: true },
    });
    const allDepartmentCodes = allDepartments.map((d) => d.code);

    const aliasMap = await this.buildAliasMap(allCourses.map((c) => c.code));

    const departmentalManualOverrideFilter: Record<string, any> = {
      sessionId: session.id,
      semester: dto.semester,
      isManualOverride: true,
    };

    const deptManualCourseCond: Record<string, any> = { isGeneral: false };

    if (departmentCode) {
      deptManualCourseCond.departmentCode = departmentCode;
    } else {
      if (collegeScope) {
        deptManualCourseCond.department = { college: collegeScope };
      }
      if (lockedDepartmentCodes.length > 0) {
        deptManualCourseCond.departmentCode = { notIn: lockedDepartmentCodes };
      }
    }

    if (level) deptManualCourseCond.level = level;
    if (programme) deptManualCourseCond.code = { startsWith: programme };

    departmentalManualOverrideFilter.course = deptManualCourseCond;

    const generalScheduledFilter: Record<string, any> = {
      sessionId: session.id,
      semester: dto.semester,
      course: { isGeneral: true, ...(level ? { level } : {}) },
    };

    const [departmentalManualOverrides, alreadyScheduledGeneral] =
      await Promise.all([
        this.prisma.schedule.findMany({
          where: departmentalManualOverrideFilter,
          include: { course: { include: { department: true } } },
        }) as Promise<Schedule[]>,
        collegeScope
          ? Promise.resolve([])
          : (this.prisma.schedule.findMany({
              where: generalScheduledFilter,
              include: { course: { include: { department: true } } },
            }) as Promise<Schedule[]>),
      ]);

    const overriddenCourseCodes = new Set<string>([
      ...departmentalManualOverrides.map((s) => s.courseCode),
      ...alreadyScheduledGeneral.map((s) => s.courseCode),
    ]);

    const coursesToSchedule: CourseInput[] = allCourses
      .filter((c) => !overriddenCourseCodes.has(c.code))
      .map((c) => ({
        courseCode: c.code,
        departmentCode: c.departmentCode,
        level: c.level,
        semester: c.semester,
        isGeneral: c.isGeneral,
        aliasedCourseCodes: aliasMap.get(c.code) ?? [],
      }));

    const allExistingSchedules = await this.prisma.schedule.findMany({
      where: { sessionId: session.id, semester: dto.semester },
      include: { course: { include: { department: true } } },
    });

    const locked: LockedSlot[] = allExistingSchedules.map((s) => ({
      courseCode: s.courseCode,
      departmentCode: s.course.departmentCode,
      level: s.course.level,
      dayOfWeek: s.dayOfWeek,
      startTime: s.startTime,
      endTime: s.endTime,
      semester: s.semester,
      isUniversityCourse: s.course.isGeneral,
      aliasedCourseCodes: aliasMap.get(s.courseCode) ?? [],
    }));

    const assignments = this.schedulerEngine.generate(
      coursesToSchedule,
      locked,
      allDepartmentCodes,
    );

    const autoDeleteDeptCourseCond: Record<string, any> = { isGeneral: false };

    if (departmentCode) {
      autoDeleteDeptCourseCond.departmentCode = departmentCode;
    } else {
      if (collegeScope) {
        autoDeleteDeptCourseCond.department = { college: collegeScope };
      }
      if (lockedDepartmentCodes.length > 0) {
        autoDeleteDeptCourseCond.departmentCode = {
          notIn: lockedDepartmentCodes,
        };
      }
    }

    if (level) autoDeleteDeptCourseCond.level = level;
    if (programme) autoDeleteDeptCourseCond.code = { startsWith: programme };

    const autoDeleteDepartmentalFilter: Record<string, any> = {
      sessionId: session.id,
      semester: dto.semester,
      isManualOverride: false,
      isAutoGenerated: true,
      isFixed: false,
      course: autoDeleteDeptCourseCond,
    };

    const autoDeleteUniversityFilter: Record<string, any> = {
      sessionId: session.id,
      semester: dto.semester,
      isManualOverride: false,
      isAutoGenerated: true,
      isFixed: false,
      course: { isGeneral: true, ...(level ? { level } : {}) },
    };

    await this.prisma.$transaction(async (tx) => {
      await tx.schedule.deleteMany({ where: autoDeleteDepartmentalFilter });
      if (!collegeScope) {
        await tx.schedule.deleteMany({ where: autoDeleteUniversityFilter });
      }

      if (assignments.length > 0) {
        await tx.schedule.createMany({
          data: assignments.map((a) => ({
            courseCode: a.courseCode,
            dayOfWeek: a.dayOfWeek,
            startTime: a.startTime,
            endTime: a.endTime,
            semester: a.semester,
            sessionId: session.id,
            isAutoGenerated: true,
            isManualOverride: false,
            isFixed: false,
          })),
          skipDuplicates: true,
        });
      }
    });

    const totalPreserved =
      departmentalManualOverrides.length + alreadyScheduledGeneral.length;

    return {
      sessionId: session.id,
      sessionName: session.name,
      semester: dto.semester,
      departmentCode,
      programme,
      level,
      totalCourses: allCourses.length,
      scheduledCourses: assignments.length + totalPreserved,
      preservedOverrides: totalPreserved,
      skippedLockedDepartments: lockedDepartmentCodes.length,
    };
  }

  async generateSchedulesBatch(
    dto: GenerateScheduleDto,
    requestingUser: { id: string; role: string; collegeCode?: College },
  ): Promise<BatchGenerateScheduleResult> {
    if (requestingUser.role === Role.HOD) {
      const result = await this.generateSchedules(dto, requestingUser);
      return {
        sessionId: result.sessionId,
        sessionName: result.sessionName,
        semester: dto.semester,
        programme: result.programme,
        totalDepartments: 1,
        processedDepartments: 1,
        skippedLockedDepartments: 0,
        totalCourses: result.totalCourses,
        scheduledCourses: result.scheduledCourses,
        preservedOverrides: result.preservedOverrides,
        errors: [],
      };
    }

    const collegeScope = this.resolveCollegeScope(requestingUser);

    const session = dto.sessionId
      ? await this.prisma.academicSession.findUnique({
          where: { id: dto.sessionId },
        })
      : await this.prisma.academicSession.findFirst({
          where: { isActive: true },
        });

    if (!session) {
      throw new NotFoundException('No active academic session found');
    }

    const lockedDepts = await this.prisma.department.findMany({
      where: { isScheduleLocked: true, isActive: true },
      select: { code: true },
    });
    const lockedCodes = new Set(lockedDepts.map((d) => d.code));

    const universityCourseFilter: Record<string, any> = {
      isActive: true,
      semester: dto.semester,
      isGeneral: true,
    };
    if (dto.level) universityCourseFilter.level = dto.level;

    const universityCourses = collegeScope
      ? []
      : await this.prisma.course.findMany({
          where: universityCourseFilter,
          include: { department: true },
        });

    const aliasMap = await this.buildAliasMap(
      universityCourses.map((c) => c.code),
    );

    const allDepartments = await this.prisma.department.findMany({
      where: { isActive: true },
      select: { code: true },
    });
    const allDepartmentCodes = allDepartments.map((d) => d.code);

    const universityCoursesInput: CourseInput[] = universityCourses.map(
      (c) => ({
        courseCode: c.code,
        departmentCode: c.departmentCode,
        level: c.level,
        semester: c.semester,
        isGeneral: true,
        aliasedCourseCodes: aliasMap.get(c.code) ?? [],
      }),
    );

    const existingUniversitySchedules = collegeScope
      ? []
      : await this.prisma.schedule.findMany({
          where: {
            sessionId: session.id,
            semester: dto.semester,
            course: { isGeneral: true },
          },
          include: { course: { include: { department: true } } },
        });

    const overriddenUniversityCodes = new Set(
      existingUniversitySchedules
        .filter((s) => s.isManualOverride)
        .map((s) => s.courseCode),
    );

    const universityToSchedule = universityCoursesInput.filter(
      (c) => !overriddenUniversityCodes.has(c.courseCode),
    );

    const universityLocked: LockedSlot[] = existingUniversitySchedules
      .filter((s) => s.isManualOverride)
      .map((s) => ({
        courseCode: s.courseCode,
        departmentCode: s.course.departmentCode,
        level: s.course.level,
        dayOfWeek: s.dayOfWeek,
        startTime: s.startTime,
        endTime: s.endTime,
        semester: s.semester,
        isUniversityCourse: true,
        aliasedCourseCodes: aliasMap.get(s.courseCode) ?? [],
      }));

    let universityAssignments: ScheduleAssignment[] = [];
    const errors: Array<{ departmentCode: string; message: string }> = [];

    if (universityToSchedule.length > 0) {
      try {
        universityAssignments = this.schedulerEngine.generate(
          universityToSchedule,
          universityLocked,
          allDepartmentCodes,
        );

        await this.prisma.$transaction(async (tx) => {
          const univDeleteFilter: Record<string, any> = {
            sessionId: session.id,
            semester: dto.semester,
            isManualOverride: false,
            isFixed: false,
            course: {
              isGeneral: true,
              ...(dto.level ? { level: dto.level } : {}),
            },
          };
          await tx.schedule.deleteMany({ where: univDeleteFilter });

          if (universityAssignments.length > 0) {
            await tx.schedule.createMany({
              data: universityAssignments.map((a) => ({
                courseCode: a.courseCode,
                dayOfWeek: a.dayOfWeek,
                startTime: a.startTime,
                endTime: a.endTime,
                semester: a.semester,
                sessionId: session.id,
                isAutoGenerated: true,
                isManualOverride: false,
                isFixed: false,
              })),
              skipDuplicates: true,
            });
          }
        });
      } catch (e: unknown) {
        if (e instanceof UnprocessableEntityException) {
          throw e;
        }
        errors.push({
          departmentCode: 'UNIVERSITY',
          message:
            e instanceof Error
              ? e.message
              : 'Failed to schedule university courses',
        });
      }
    }

    const allUniversitySchedules = collegeScope
      ? []
      : await this.prisma.schedule.findMany({
          where: {
            sessionId: session.id,
            semester: dto.semester,
            course: { isGeneral: true },
          },
          include: { course: { include: { department: true } } },
        });

    const globalUniversityLocked: LockedSlot[] = allUniversitySchedules.map(
      (s) => ({
        courseCode: s.courseCode,
        departmentCode: s.course.departmentCode,
        level: s.course.level,
        dayOfWeek: s.dayOfWeek,
        startTime: s.startTime,
        endTime: s.endTime,
        semester: s.semester,
        isUniversityCourse: true,
        aliasedCourseCodes: aliasMap.get(s.courseCode) ?? [],
      }),
    );

    const departmentFilter: Record<string, any> = {
      isActive: true,
      code: { notIn: Array.from(lockedCodes) },
    };

    if (dto.departmentCode) {
      departmentFilter.code = dto.departmentCode;
    } else if (collegeScope) {
      departmentFilter.college = collegeScope;
      if (lockedCodes.size > 0) {
        departmentFilter.code = { notIn: Array.from(lockedCodes) };
      }
    }

    const departments = dto.departmentCode
      ? [{ code: dto.departmentCode }]
      : await this.prisma.department.findMany({
          where: departmentFilter,
          select: { code: true },
          orderBy: { code: 'asc' },
        });

    let totalCourses = 0;
    let scheduledCourses =
      universityAssignments.length + overriddenUniversityCodes.size;
    let preservedOverrides = overriddenUniversityCodes.size;
    let processedDepartments = 0;

    for (const dept of departments) {
      try {
        const deptCourseFilter: Record<string, any> = {
          isActive: true,
          semester: dto.semester,
          isGeneral: false,
          departmentCode: dept.code,
        };
        if (dto.level) deptCourseFilter.level = dto.level;
        if (dto.programme)
          deptCourseFilter.code = { startsWith: dto.programme };

        const deptCourses = await this.prisma.course.findMany({
          where: deptCourseFilter,
          include: { department: true },
        });

        if (deptCourses.length === 0) {
          processedDepartments++;
          continue;
        }

        totalCourses += deptCourses.length;

        const deptAliasMap = await this.buildAliasMap(
          deptCourses.map((c) => c.code),
        );

        const deptManualCourseFilter: Record<string, any> = {
          departmentCode: dept.code,
          isGeneral: false,
        };
        if (dto.level) deptManualCourseFilter.level = dto.level;
        if (dto.programme)
          deptManualCourseFilter.code = { startsWith: dto.programme };

        const deptManualOverrides = await this.prisma.schedule.findMany({
          where: {
            sessionId: session.id,
            semester: dto.semester,
            isManualOverride: true,
            course: deptManualCourseFilter,
          },
          include: { course: { include: { department: true } } },
        });

        const overriddenDeptCodes = new Set(
          deptManualOverrides.map((s) => s.courseCode),
        );
        preservedOverrides += overriddenDeptCodes.size;

        const deptCoursesInput: CourseInput[] = deptCourses
          .filter((c) => !overriddenDeptCodes.has(c.code))
          .map((c) => ({
            courseCode: c.code,
            departmentCode: c.departmentCode,
            level: c.level,
            semester: c.semester,
            isGeneral: false,
            aliasedCourseCodes: deptAliasMap.get(c.code) ?? [],
          }));

        const existingDeptSchedules = await this.prisma.schedule.findMany({
          where: {
            sessionId: session.id,
            semester: dto.semester,
            course: { isGeneral: false, departmentCode: dept.code },
          },
          include: { course: { include: { department: true } } },
        });

        const deptLocked: LockedSlot[] = [
          ...globalUniversityLocked,
          ...existingDeptSchedules.map((s) => ({
            courseCode: s.courseCode,
            departmentCode: s.course.departmentCode,
            level: s.course.level,
            dayOfWeek: s.dayOfWeek,
            startTime: s.startTime,
            endTime: s.endTime,
            semester: s.semester,
            isUniversityCourse: false,
            aliasedCourseCodes: deptAliasMap.get(s.courseCode) ?? [],
          })),
        ];

        if (deptCoursesInput.length === 0) {
          scheduledCourses += overriddenDeptCodes.size;
          processedDepartments++;
          continue;
        }

        const deptAssignments = this.schedulerEngine.generate(
          deptCoursesInput,
          deptLocked,
          allDepartmentCodes,
        );

        await this.prisma.$transaction(async (tx) => {
          const deleteCourseFilter: Record<string, any> = {
            departmentCode: dept.code,
            isGeneral: false,
          };
          if (dto.level) deleteCourseFilter.level = dto.level;
          if (dto.programme)
            deleteCourseFilter.code = { startsWith: dto.programme };

          await tx.schedule.deleteMany({
            where: {
              sessionId: session.id,
              semester: dto.semester,
              isManualOverride: false,
              isFixed: false,
              course: deleteCourseFilter,
            },
          });

          if (deptAssignments.length > 0) {
            await tx.schedule.createMany({
              data: deptAssignments.map((a) => ({
                courseCode: a.courseCode,
                dayOfWeek: a.dayOfWeek,
                startTime: a.startTime,
                endTime: a.endTime,
                semester: a.semester,
                sessionId: session.id,
                isAutoGenerated: true,
                isManualOverride: false,
                isFixed: false,
              })),
              skipDuplicates: true,
            });
          }
        });

        scheduledCourses += deptAssignments.length + overriddenDeptCodes.size;
        processedDepartments++;
      } catch (e: unknown) {
        errors.push({
          departmentCode: dept.code,
          message: e instanceof Error ? e.message : 'Scheduling failed',
        });
        processedDepartments++;
      }
    }

    totalCourses += universityCourses.length;

    return {
      sessionId: session.id,
      sessionName: session.name,
      semester: dto.semester,
      programme: dto.programme ?? null,
      totalDepartments: departments.length,
      processedDepartments,
      skippedLockedDepartments: lockedCodes.size,
      totalCourses,
      scheduledCourses,
      preservedOverrides,
      errors,
    };
  }

  private resolveCollegeScope(requestingUser: {
    role: string;
    collegeCode?: College;
  }): College | null {
    if (
      requestingUser.role === Role.COLLEGE_ADMIN &&
      requestingUser.collegeCode
    ) {
      return requestingUser.collegeCode;
    }
    return null;
  }

  private async buildAliasMap(
    courseCodes: string[],
  ): Promise<Map<string, string[]>> {
    if (courseCodes.length === 0) return new Map();

    const aliases = await this.prisma.courseAlias.findMany({
      where: {
        OR: [
          { primaryCode: { in: courseCodes } },
          { aliasCode: { in: courseCodes } },
        ],
      },
      select: { primaryCode: true, aliasCode: true },
    });

    const map = new Map<string, string[]>();
    for (const a of aliases) {
      if (!map.has(a.primaryCode)) map.set(a.primaryCode, []);
      if (!map.has(a.aliasCode)) map.set(a.aliasCode, []);
      map.get(a.primaryCode)!.push(a.aliasCode);
      map.get(a.aliasCode)!.push(a.primaryCode);
    }
    return map;
  }

  async getScheduleStatistics() {
    return this.scheduleRepository.getScheduleStats();
  }

  async toggleFixed(
    id: string,
    requestingUser: { id: string; role: string; collegeCode?: College },
  ): Promise<Schedule> {
    const schedule = await this.prisma.schedule.findUnique({
      where: { id },
      include: {
        course: {
          include: {
            department: true,
            lecturer: { select: { id: true, name: true, email: true } },
          },
        },
      },
    });

    if (!schedule) {
      throw new NotFoundException(`Schedule '${id}' not found`);
    }

    if (requestingUser.role === Role.HOD) {
      const hodUser = await this.prisma.user.findUnique({
        where: { id: requestingUser.id },
        include: { managedDepartment: true },
      });

      if (!hodUser?.managedDepartment) {
        throw new ForbiddenException('HOD must be assigned to a department');
      }

      if (schedule.course.departmentCode !== hodUser.managedDepartment.code) {
        throw new ForbiddenException(
          'HODs can only pin or unpin schedules in their own department',
        );
      }
    }

    if (requestingUser.role === Role.COLLEGE_ADMIN) {
      if (
        !requestingUser.collegeCode ||
        (schedule.course.department as unknown as { college: College })
          .college !== requestingUser.collegeCode
      ) {
        throw new ForbiddenException(
          'College admins can only pin or unpin schedules within their own college',
        );
      }
    }

    return this.prisma.schedule.update({
      where: { id },
      data: { isFixed: !schedule.isFixed },
      include: {
        course: {
          include: {
            department: true,
            lecturer: { select: { id: true, name: true, email: true } },
          },
        },
      },
    });
  }

  private async resolveLockedDepartmentCodes(
    departmentCode: string | null,
  ): Promise<string[]> {
    if (departmentCode !== null) return [];

    const lockedDepts = await this.prisma.department.findMany({
      where: { isScheduleLocked: true, isActive: true },
      select: { code: true },
    });

    return lockedDepts.map((d) => d.code);
  }

  private validateTimeSlot(
    startTime: string,
    endTime: string,
    dayOfWeek?: DayOfWeek,
  ): void {
    if (dayOfWeek === DayOfWeek.SATURDAY || dayOfWeek === DayOfWeek.SUNDAY) {
      throw new BadRequestException('Weekend classes are not allowed');
    }

    const [startHour, startMin] = startTime.split(':').map(Number);
    const [endHour, endMin] = endTime.split(':').map(Number);

    if (startMin !== 0 || endMin !== 0) {
      throw new BadRequestException(
        'Class times must be on the hour (e.g. 09:00, 11:00)',
      );
    }

    const duration = endHour - startHour;

    if (duration < 1) {
      throw new BadRequestException('End time must be after start time');
    }

    if (startHour < 9 || endHour > 19) {
      throw new BadRequestException('Classes must run between 09:00 and 19:00');
    }

    if (dayOfWeek === DayOfWeek.WEDNESDAY && endHour > 15) {
      throw new BadRequestException('Wednesday classes must end by 15:00');
    }
  }

  private async checkUniversityCourseClash(
    courseLevel: Level,
    dayOfWeek: DayOfWeek,
    startTime: string,
    endTime: string,
    sessionId: string,
    excludeScheduleId?: string,
  ): Promise<void> {
    const fixedUniversitySchedules = await this.prisma.schedule.findMany({
      where: {
        sessionId,
        dayOfWeek,
        isFixed: true,
        ...(excludeScheduleId && { id: { not: excludeScheduleId } }),
        course: {
          isGeneral: true,
          level: courseLevel,
        },
      },
      include: {
        course: { select: { code: true, name: true } },
      },
    });

    if (fixedUniversitySchedules.length === 0) return;

    const candidateStart = this.timeToMinutes(startTime);
    const candidateEnd = this.timeToMinutes(endTime);

    for (const fixed of fixedUniversitySchedules) {
      const fixedStart = this.timeToMinutes(fixed.startTime);
      const fixedEnd = this.timeToMinutes(fixed.endTime);

      const overlaps = candidateStart < fixedEnd && fixedStart < candidateEnd;

      if (overlaps) {
        throw new ConflictException(
          `Time slot ${startTime}-${endTime} on ${dayOfWeek} conflicts with university course ` +
            `${fixed.course.code} (${fixed.course.name}) fixed at ${fixed.startTime}-${fixed.endTime}. ` +
            `All ${courseLevel} courses must avoid this window.`,
        );
      }
    }
  }

  private timeToMinutes(time: string): number {
    const [hours, minutes] = time.split(':').map(Number);
    return hours * 60 + minutes;
  }
}
