import {
  Injectable,
  ConflictException,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { PrismaService } from '../database/prisma.service';
import { CreateScheduleDto } from './dto/create-schedule.dto';
import { UpdateScheduleDto } from './dto/update-schedule.dto';
import { ScheduleFilterDto } from './dto/schedule-filter.dto';
import { GenerateScheduleDto, GenerateScheduleResult } from './dto/generate-schedule.dto';
import { BaseService } from '../../common/services/base.service';
import { ScheduleRepository } from './repositories/schedule.repository';
import { SchedulerEngine, LockedSlot, CourseInput } from './scheduler/scheduler.engine';
import { DayOfWeek, Schedule, Semester } from '../../generated/prisma';
import { PaginatedResult } from '../../common/interfaces/base-service.interface';

@Injectable()
export class SchedulesService extends BaseService<
  Schedule,
  CreateScheduleDto,
  UpdateScheduleDto
> {
  constructor(
    prisma: PrismaService,
    private readonly scheduleRepository: ScheduleRepository,
    private readonly schedulerEngine: SchedulerEngine,
  ) {
    super(prisma, {
      modelName: 'schedule',
      identifierField: 'id',
      includeRelations: {
        course: {
          include: { department: true },
        },
      },
      defaultOrderBy: { dayOfWeek: 'asc' },
    });
  }

  protected async beforeCreate(dto: CreateScheduleDto): Promise<Record<string, any>> {
    const activeSession = await this.prisma.academicSession.findFirst({
      where: { isActive: true },
    });

    if (!activeSession) {
      throw new ConflictException('No active academic session found');
    }

    const course = await this.prisma.course.findUnique({
      where: { code: dto.courseCode },
      select: { semester: true },
    });

    if (!course) {
      throw new NotFoundException(`Course '${dto.courseCode}' not found`);
    }

    this.validateTimeSlot(dto.startTime, dto.endTime, dto.dayOfWeek);

    const existing = await this.scheduleRepository.findConflict(
      dto.courseCode,
      activeSession.id,
    );

    if (existing) {
      throw new ConflictException(
        `Course '${dto.courseCode}' already has a schedule this session. Update the existing one.`,
      );
    }

    return {
      ...dto,
      sessionId: activeSession.id,
      semester: course.semester,
      isAutoGenerated: false,
      isManualOverride: true,
    };
  }

  protected async beforeUpdate(
    dto: UpdateScheduleDto,
    identifier: string,
  ): Promise<Record<string, any>> {
    const current = await this.prisma.schedule.findUnique({
      where: { id: identifier },
    });

    if (!current) {
      throw new NotFoundException(`Schedule '${identifier}' not found`);
    }

    const resolvedDay = dto.dayOfWeek ?? current.dayOfWeek;
    const resolvedStart = dto.startTime ?? current.startTime;
    const resolvedEnd = dto.endTime ?? current.endTime;

    this.validateTimeSlot(resolvedStart, resolvedEnd, resolvedDay);

    return {
      ...dto,
      isManualOverride: true,
      isAutoGenerated: false,
    };
  }

  async findAll(
    query: ScheduleFilterDto = {},
  ): Promise<Schedule[] | PaginatedResult<Schedule>> {
    const where: Record<string, any> = {};

    if (query.semester) where.semester = query.semester;

    if (query.sessionId) {
      where.sessionId = query.sessionId;
    } else {
      const activeSession = await this.prisma.academicSession.findFirst({
        where: { isActive: true },
      });
      if (activeSession) where.sessionId = activeSession.id;
    }

    if (query.courseCode) where.courseCode = query.courseCode;
    if (query.dayOfWeek) where.dayOfWeek = query.dayOfWeek;

    const courseFilter: Record<string, any> = {};
    if (query.departmentCode) courseFilter.departmentCode = query.departmentCode;
    if (query.level) courseFilter.level = query.level;
    if (Object.keys(courseFilter).length > 0) where.course = courseFilter;

    if (query.startTime) where.startTime = { gte: query.startTime };
    if (query.endTime) where.endTime = { lte: query.endTime };

    if (query.page && query.limit) return this.findPaginated(where, query);

    return this.getModel().findMany({
      where,
      include: this.config.includeRelations,
      orderBy: [{ dayOfWeek: 'asc' }, { startTime: 'asc' }],
    }) as Promise<Schedule[]>;
  }

  async generateSchedules(dto: GenerateScheduleDto): Promise<GenerateScheduleResult> {
    const session = dto.sessionId
      ? await this.prisma.academicSession.findUnique({ where: { id: dto.sessionId } })
      : await this.prisma.academicSession.findFirst({ where: { isActive: true } });

    if (!session) {
      throw new NotFoundException(
        dto.sessionId
          ? `Session '${dto.sessionId}' not found`
          : 'No active academic session found',
      );
    }

    const allCourses = await this.prisma.course.findMany({
      where: { isActive: true, semester: dto.semester },
      include: { department: true },
    });

    if (allCourses.length === 0) {
      return {
        sessionId: session.id,
        sessionName: session.name,
        semester: dto.semester,
        totalCourses: 0,
        scheduledCourses: 0,
        preservedOverrides: 0,
      };
    }

    const manualOverrides = await this.prisma.schedule.findMany({
      where: {
        sessionId: session.id,
        semester: dto.semester,
        isManualOverride: true,
      },
      include: { course: { include: { department: true } } },
    });

    const overriddenCourseCodes = new Set(manualOverrides.map((s) => s.courseCode));

    await this.prisma.schedule.deleteMany({
      where: {
        sessionId: session.id,
        semester: dto.semester,
        isManualOverride: false,
        isAutoGenerated: true,
      },
    });

    const coursesToSchedule: CourseInput[] = allCourses
      .filter((c) => !overriddenCourseCodes.has(c.code))
      .map((c) => ({
        courseCode: c.code,
        departmentCode: c.departmentCode,
        level: c.level,
        semester: c.semester,
      }));

    const locked: LockedSlot[] = manualOverrides.map((s) => ({
      courseCode: s.courseCode,
      departmentCode: s.course.departmentCode,
      level: s.course.level,
      dayOfWeek: s.dayOfWeek,
      startTime: s.startTime,
      endTime: s.endTime,
      semester: s.semester,
    }));

    const assignments = this.schedulerEngine.generate(coursesToSchedule, locked);

    if (assignments.length > 0) {
      await this.prisma.schedule.createMany({
        data: assignments.map((a) => ({
          courseCode: a.courseCode,
          dayOfWeek: a.dayOfWeek,
          startTime: a.startTime,
          endTime: a.endTime,
          semester: a.semester,
          sessionId: session.id,
          isAutoGenerated: true,
          isManualOverride: false,
        })),
      });
    }

    return {
      sessionId: session.id,
      sessionName: session.name,
      semester: dto.semester,
      totalCourses: allCourses.length,
      scheduledCourses: assignments.length + manualOverrides.length,
      preservedOverrides: manualOverrides.length,
    };
  }

  async getScheduleStatistics() {
    return this.scheduleRepository.getScheduleStats();
  }

  private validateTimeSlot(
    startTime: string,
    endTime: string,
    dayOfWeek?: DayOfWeek,
  ): void {
    if (dayOfWeek === DayOfWeek.SATURDAY || dayOfWeek === DayOfWeek.SUNDAY) {
      throw new BadRequestException('Weekend classes are not allowed');
    }

    const validStarts = ['09:00', '11:00', '13:00', '15:00', '17:00'];

    if (!validStarts.includes(startTime)) {
      throw new BadRequestException(
        `Start time must be one of: ${validStarts.join(', ')}`,
      );
    }

    const [startHour] = startTime.split(':').map(Number);
    const [endHour] = endTime.split(':').map(Number);

    if (endHour - startHour !== 2) {
      throw new BadRequestException('Class duration must be exactly 2 hours');
    }

    if (startHour < 9 || endHour > 19) {
      throw new BadRequestException('Classes must run between 09:00 and 19:00');
    }

    if (dayOfWeek === DayOfWeek.WEDNESDAY && startHour >= 15) {
      throw new BadRequestException(
        'Wednesday classes cannot start at or after 15:00 due to chapel',
      );
    }
  }
}
