import { applyDecorators } from '@nestjs/common';
import { ApiOperation, ApiResponse, ApiParam } from '@nestjs/swagger';
import { DayOfWeek, Semester } from '../../../generated/prisma';
import {
  ApiStandardResponses,
  ApiAuthRequired,
  ApiNotFoundResponse,
  ApiStatisticsResponse,
} from '../../../common/decorators/base-api.decorator';

export const ApiGetSchedules = () =>
  applyDecorators(
    ApiOperation({
      summary: 'Get all schedules',
      description:
        'Retrieve schedules for the active session with optional filtering. Defaults to the active academic session.',
    }),
    ApiResponse({
      status: 200,
      description: 'Schedules retrieved successfully',
      schema: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            courseCode: { type: 'string', example: 'CSC101' },
            dayOfWeek: { type: 'string', enum: Object.values(DayOfWeek) },
            startTime: { type: 'string', example: '09:00' },
            endTime: { type: 'string', example: '11:00' },
            semester: { type: 'string', enum: Object.values(Semester) },
            isAutoGenerated: { type: 'boolean', example: true },
            isManualOverride: { type: 'boolean', example: false },
            course: {
              type: 'object',
              properties: {
                code: { type: 'string' },
                name: { type: 'string' },
                level: { type: 'string' },
                department: {
                  type: 'object',
                  properties: {
                    code: { type: 'string' },
                    name: { type: 'string' },
                  },
                },
              },
            },
          },
        },
      },
    }),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiGetScheduleById = () =>
  applyDecorators(
    ApiOperation({ summary: 'Get schedule by ID' }),
    ApiParam({ name: 'id', type: 'string', format: 'uuid' }),
    ApiResponse({ status: 200, description: 'Schedule retrieved successfully' }),
    ApiNotFoundResponse('Schedule'),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiCreateSchedule = () =>
  applyDecorators(
    ApiOperation({
      summary: 'Create a schedule manually',
      description:
        'Manually assign a course to a time slot. The slot must be a valid 2-hour block starting on the hour (09:00, 11:00, 13:00, 15:00, 17:00). ' +
        'On Wednesdays, only 09:00, 11:00, and 13:00 are valid. This marks the schedule as a manual override.',
    }),
    ApiResponse({ status: 201, description: 'Schedule created successfully' }),
    ApiResponse({
      status: 409,
      description: 'Course already has a schedule this session',
    }),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiUpdateSchedule = () =>
  applyDecorators(
    ApiOperation({
      summary: 'Update a schedule',
      description: 'Update a schedule entry. Automatically marks it as a manual override.',
    }),
    ApiParam({ name: 'id', type: 'string', format: 'uuid' }),
    ApiResponse({ status: 200, description: 'Schedule updated successfully' }),
    ApiNotFoundResponse('Schedule'),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiDeleteSchedule = () =>
  applyDecorators(
    ApiOperation({ summary: 'Delete a schedule' }),
    ApiParam({ name: 'id', type: 'string', format: 'uuid' }),
    ApiResponse({ status: 200, description: 'Schedule deleted successfully' }),
    ApiNotFoundResponse('Schedule'),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiGetScheduleStatistics = () =>
  applyDecorators(
    ApiOperation({ summary: 'Get schedule statistics' }),
    ApiResponse({
      status: 200,
      description: 'Statistics retrieved successfully',
      schema: ApiStatisticsResponse({
        totalSchedules: { type: 'number', example: 120 },
        autoGenerated: { type: 'number', example: 110 },
        manualOverrides: { type: 'number', example: 10 },
        schedulesByDay: {
          type: 'object',
          additionalProperties: { type: 'number' },
        },
      }),
    }),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiGenerateSchedules = () =>
  applyDecorators(
    ApiOperation({
      summary: 'Auto-generate schedules',
      description:
        'Runs the scheduling algorithm for all active courses in the given semester. ' +
        'Clears existing auto-generated schedules and re-assigns them while preserving any manual overrides. ' +
        'Throws 422 if a valid schedule cannot be constructed for all courses.',
    }),
    ApiResponse({
      status: 201,
      description: 'Schedules generated successfully',
      schema: {
        type: 'object',
        properties: {
          sessionId: { type: 'string' },
          sessionName: { type: 'string', example: '2024/2025' },
          semester: { type: 'string', enum: Object.values(Semester) },
          totalCourses: { type: 'number', example: 178 },
          scheduledCourses: { type: 'number', example: 178 },
          preservedOverrides: { type: 'number', example: 3 },
        },
      },
    }),
    ApiResponse({
      status: 422,
      description: 'Unprocessable — not enough slots to schedule all courses',
    }),
    ApiNotFoundResponse('Active session'),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );
