import { applyDecorators } from '@nestjs/common';
import { ApiOperation, ApiResponse, ApiParam } from '@nestjs/swagger';
import { DayOfWeek, Semester, SessionType } from '../../../generated/prisma';
import {
  ApiStandardResponses,
  ApiAuthRequired,
  ApiNotFoundResponse,
  ApiStatisticsResponse,
} from '../../../common/decorators/base-api.decorator';

export const ApiGetSchedules = () =>
  applyDecorators(
    ApiOperation({
      summary: 'Get all schedules',
      description:
        'Retrieve schedules for the active session with optional filtering. Defaults to the active academic session.',
    }),
    ApiResponse({
      status: 200,
      description: 'Schedules retrieved successfully',
      schema: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            courseCode: { type: 'string', example: 'CSC101' },
            dayOfWeek: { type: 'string', enum: Object.values(DayOfWeek) },
            startTime: { type: 'string', example: '09:00' },
            endTime: { type: 'string', example: '11:00' },
            semester: { type: 'string', enum: Object.values(Semester) },
            isAutoGenerated: { type: 'boolean', example: true },
            isManualOverride: { type: 'boolean', example: false },
            sessionType: {
              type: 'string',
              enum: Object.values(SessionType),
              example: 'THEORY',
            },
            course: {
              type: 'object',
              properties: {
                code: { type: 'string' },
                name: { type: 'string' },
                level: { type: 'string' },
                department: {
                  type: 'object',
                  properties: {
                    code: { type: 'string' },
                    name: { type: 'string' },
                  },
                },
              },
            },
          },
        },
      },
    }),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiGetScheduleById = () =>
  applyDecorators(
    ApiOperation({ summary: 'Get schedule by ID' }),
    ApiParam({ name: 'id', type: 'string', format: 'uuid' }),
    ApiResponse({
      status: 200,
      description: 'Schedule retrieved successfully',
    }),
    ApiNotFoundResponse('Schedule'),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiCreateSchedule = () =>
  applyDecorators(
    ApiOperation({
      summary: 'Create a schedule manually',
      description:
        'Manually assign a course to a time slot. The slot must be a valid 2-hour block starting on the hour (09:00, 11:00, 13:00, 15:00, 17:00). ' +
        'On Wednesdays, only 09:00, 11:00, and 13:00 are valid. This marks the schedule as a manual override.',
    }),
    ApiResponse({ status: 201, description: 'Schedule created successfully' }),
    ApiResponse({
      status: 409,
      description: 'Course already has a schedule this session',
    }),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiUpdateSchedule = () =>
  applyDecorators(
    ApiOperation({
      summary: 'Update a schedule',
      description:
        'Update a schedule entry. Automatically marks it as a manual override.',
    }),
    ApiParam({ name: 'id', type: 'string', format: 'uuid' }),
    ApiResponse({ status: 200, description: 'Schedule updated successfully' }),
    ApiNotFoundResponse('Schedule'),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiDeleteSchedule = () =>
  applyDecorators(
    ApiOperation({ summary: 'Delete a schedule' }),
    ApiParam({ name: 'id', type: 'string', format: 'uuid' }),
    ApiResponse({ status: 200, description: 'Schedule deleted successfully' }),
    ApiNotFoundResponse('Schedule'),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiGetScheduleStatistics = () =>
  applyDecorators(
    ApiOperation({ summary: 'Get schedule statistics' }),
    ApiResponse({
      status: 200,
      description: 'Statistics retrieved successfully',
      schema: ApiStatisticsResponse({
        totalSchedules: { type: 'number', example: 120 },
        autoGenerated: { type: 'number', example: 110 },
        manualOverrides: { type: 'number', example: 10 },
        schedulesByDay: {
          type: 'object',
          additionalProperties: { type: 'number' },
        },
      }),
    }),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiGenerateSchedules = () =>
  applyDecorators(
    ApiOperation({
      summary: 'Auto-generate schedules',
      description:
        'Runs the scheduling algorithm for all active courses in the given semester. ' +
        'Clears existing auto-generated schedules and re-assigns them while preserving manual overrides. ' +
        'Departments with isScheduleLocked set to true are skipped entirely during system-wide generation, ' +
        'but their existing schedules are still respected as occupied slots to prevent conflicts. ' +
        'Throws 422 if a valid schedule cannot be constructed for all eligible courses.',
    }),
    ApiResponse({
      status: 201,
      description: 'Schedules generated successfully',
      schema: {
        type: 'object',
        properties: {
          sessionId: { type: 'string' },
          sessionName: { type: 'string', example: '2024/2025' },
          semester: { type: 'string', enum: Object.values(Semester) },
          departmentCode: {
            type: 'string',
            nullable: true,
            example: null,
            description: 'null when generated system-wide',
          },
          totalCourses: { type: 'number', example: 178 },
          scheduledCourses: { type: 'number', example: 165 },
          preservedOverrides: { type: 'number', example: 3 },
          skippedLockedDepartments: {
            type: 'number',
            example: 2,
            description:
              'Number of departments skipped because their schedule is locked',
          },
        },
      },
    }),
    ApiResponse({
      status: 422,
      description: 'Unprocessable — not enough slots to schedule all courses',
    }),
    ApiNotFoundResponse('Active session'),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiToggleScheduleFixed = () =>
  applyDecorators(
    ApiOperation({
      summary: 'Toggle isFixed on a schedule',
      description:
        'Pins or unpins a schedule slot. Pinned slots are never moved or deleted by the auto-generation algorithm. ' +
        'HODs may only pin/unpin schedules belonging to their own department.',
    }),
    ApiParam({ name: 'id', type: 'string', format: 'uuid' }),
    ApiResponse({
      status: 200,
      description: 'Schedule fixed status toggled successfully',
      schema: {
        type: 'object',
        properties: {
          id: { type: 'string', format: 'uuid' },
          courseCode: { type: 'string', example: 'CSC301' },
          isFixed: { type: 'boolean', example: true },
          dayOfWeek: { type: 'string' },
          startTime: { type: 'string', example: '09:00' },
          endTime: { type: 'string', example: '11:00' },
        },
      },
    }),
    ApiResponse({
      status: 403,
      description:
        'Forbidden — HOD attempted to pin a schedule outside their department',
    }),
    ApiNotFoundResponse('Schedule'),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiGenerateSchedulesBatch = () =>
  applyDecorators(
    ApiOperation({
      summary: 'Auto-generate schedules (batched by department)',
      description:
        'Generates schedules department-by-department to avoid timeouts on large datasets. ' +
        'University courses are processed first, then each department independently. ' +
        'Partial failures are returned in the errors array rather than aborting the whole run. ' +
        'Recommended for system-wide generation with large course catalogs.',
    }),
    ApiResponse({
      status: 201,
      description: 'Batch schedule generation completed',
      schema: {
        type: 'object',
        properties: {
          sessionId: { type: 'string' },
          sessionName: { type: 'string', example: '2024/2025' },
          semester: { type: 'string', enum: Object.values(Semester) },
          totalDepartments: { type: 'number', example: 58 },
          processedDepartments: { type: 'number', example: 56 },
          skippedLockedDepartments: { type: 'number', example: 2 },
          totalCourses: { type: 'number', example: 718 },
          scheduledCourses: { type: 'number', example: 712 },
          preservedOverrides: { type: 'number', example: 6 },
          errors: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                departmentCode: { type: 'string' },
                message: { type: 'string' },
              },
            },
          },
        },
      },
    }),
    ApiNotFoundResponse('Active session'),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );

export const ApiRecommendUniversitySlots = () =>
  applyDecorators(
    ApiOperation({
      summary: 'Recommend non-clashing weekday slots for university courses',
      description:
        'Computes recommended Monday-Thursday day and time slots for the given general/university course codes that are not eligible for automatic Friday scheduling, based on existing schedules at the same level and semester. Courses for which no free slot is available are returned with hasConflict set to true and must be scheduled manually.',
    }),
    ApiResponse({
      status: 201,
      description: 'Recommended slots computed successfully',
      schema: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            courseCode: { type: 'string', example: 'PIF101' },
            dayOfWeek: { type: 'string', example: 'MONDAY' },
            startTime: { type: 'string', example: '09:00' },
            endTime: { type: 'string', example: '11:00' },
            hasConflict: { type: 'boolean', example: false },
          },
        },
      },
    }),
    ApiNotFoundResponse('Active session'),
    ApiStandardResponses(),
    ApiAuthRequired(),
  );
