import { College } from '../../../generated/prisma';

export const DEPARTMENTS_SEED = [
  {
    name: 'Administration',
    code: 'ADM',
    college: College.CHMS,
    description: 'University administration',
  },
  {
    name: 'Accounting',
    code: 'ACC',
    college: College.CHMS,
    description: 'Department of Accounting',
  },
  {
    name: 'Business Administration',
    code: 'BUA',
    college: College.CHMS,
    description: 'Department of Business Administration',
  },
  {
    name: 'Business Studies',
    code: 'BUS',
    college: College.CHMS,
    description: 'Department of Business Studies',
  },
  {
    name: 'Banking and Finance',
    code: 'BFN',
    college: College.CHMS,
    description: 'Department of Banking and Finance',
  },
  {
    name: 'Economics',
    code: 'ECO',
    college: College.CHMS,
    description: 'Department of Economics',
  },
  {
    name: 'English',
    code: 'ENG',
    college: College.CHMS,
    description: 'Department of English',
  },
  {
    name: 'Employee and Human Relations',
    code: 'EHR',
    college: College.CHMS,
    description: 'Department of Employee and Human Relations',
  },
  {
    name: 'Entrepreneurship',
    code: 'ENT',
    college: College.CHMS,
    description: 'Department of Entrepreneurship',
  },
  {
    name: 'Fine and Applied Arts',
    code: 'FAA',
    college: College.CHMS,
    description: 'Department of Fine and Applied Arts',
  },
  {
    name: 'Finance',
    code: 'FIN',
    college: College.CHMS,
    description: 'Department of Finance',
  },
  {
    name: 'Faculty Accounting and Commerce',
    code: 'FAC',
    college: College.CHMS,
    description: 'Faculty of Accounting and Commerce',
  },
  {
    name: 'General Studies',
    code: 'GST',
    college: College.CHMS,
    description: 'General Studies unit',
  },
  {
    name: 'International Relations and Studies',
    code: 'IRS',
    college: College.CHMS,
    description: 'Department of International Relations and Studies',
  },
  {
    name: 'Information and Project Management',
    code: 'IPM',
    college: College.CHMS,
    description: 'Department of Information and Project Management',
  },
  {
    name: 'Literature',
    code: 'LIT',
    college: College.CHMS,
    description: 'Department of Literature',
  },
  {
    name: 'Mass Communication',
    code: 'MCM',
    college: College.CHMS,
    description: 'Department of Mass Communication',
  },
  {
    name: 'Music',
    code: 'MUS',
    college: College.CHMS,
    description: 'Department of Music',
  },
  {
    name: 'Philosophy',
    code: 'PHL',
    college: College.CHMS,
    description: 'Department of Philosophy',
  },
  {
    name: 'Public Administration',
    code: 'PAD',
    college: College.CHMS,
    description: 'Department of Public Administration',
  },
  {
    name: 'Pentecostal and Intercultural Formation',
    code: 'PIF',
    college: College.CHMS,
    description: 'Pentecostal and Intercultural Formation unit',
  },
  {
    name: 'Psychology',
    code: 'PSY',
    college: College.CHMS,
    description: 'Department of Psychology',
  },
  {
    name: 'Religion',
    code: 'REL',
    college: College.CHMS,
    description: 'Department of Religion',
  },
  {
    name: 'Simulation',
    code: 'SIM',
    college: College.CHMS,
    description: 'Department of Simulation',
  },
  {
    name: 'Social Sciences',
    code: 'SSC',
    college: College.CHMS,
    description: 'Department of Social Sciences',
  },
  {
    name: 'Sustainable Development',
    code: 'SDN',
    college: College.CHMS,
    description: 'Sustainable Development unit',
  },
  {
    name: 'Sociology',
    code: 'SOC',
    college: College.CHMS,
    description: 'Department of Sociology',
  },
  {
    name: 'Faculty of Management',
    code: 'FMA',
    college: College.CHMS,
    description: 'Faculty of Management',
  },
  {
    name: 'Earth and Environmental Sciences',
    code: 'ESM',
    college: College.CHMS,
    description: 'Earth and Environmental Sciences unit',
  },
  {
    name: 'Anatomy',
    code: 'ANA',
    college: College.CAHS,
    description: 'Department of Anatomy',
  },
  {
    name: 'Biochemistry',
    code: 'BCH',
    college: College.CAHS,
    description: 'Department of Biochemistry',
  },
  {
    name: 'Biomedical Engineering',
    code: 'BME',
    college: College.CAHS,
    description: 'Department of Biomedical Engineering',
  },
  {
    name: 'General Engineering and Technology',
    code: 'GET',
    college: College.CAHS,
    description: 'Department of General Engineering and Technology',
  },
  {
    name: 'Industrial and Rehabilitation Medicine',
    code: 'IRM',
    college: College.CAHS,
    description: 'Department of Industrial and Rehabilitation Medicine',
  },
  {
    name: 'Medical Laboratory Science',
    code: 'MLS',
    college: College.CAHS,
    description: 'Department of Medical Laboratory Science',
  },
  {
    name: 'Microbiology',
    code: 'MCB',
    college: College.CAHS,
    description: 'Department of Microbiology',
  },
  {
    name: 'Nursing Science',
    code: 'NSC',
    college: College.CAHS,
    description: 'Department of Nursing Science',
  },
  {
    name: 'Nutrition and Dietetics',
    code: 'NUT',
    college: College.CAHS,
    description: 'Department of Nutrition and Dietetics',
  },
  {
    name: 'Pharmacy',
    code: 'PHA',
    college: College.CAHS,
    description: 'Department of Pharmacy',
  },
  {
    name: 'Physiology',
    code: 'PHS',
    college: College.CAHS,
    description: 'Department of Physiology',
  },
  {
    name: 'Physiology and Anatomy',
    code: 'PIO',
    college: College.CAHS,
    description: 'Department of Physiology and Anatomy (combined)',
  },
  {
    name: 'Agronomy',
    code: 'AGG',
    college: College.CBAS,
    description: 'Department of Agronomy',
  },
  {
    name: 'Biology',
    code: 'BIO',
    college: College.CBAS,
    description: 'Department of Biology',
  },
  {
    name: 'Biotechnology',
    code: 'BTG',
    college: College.CBAS,
    description: 'Department of Biotechnology',
  },
  {
    name: 'Chemistry',
    code: 'CHM',
    college: College.CBAS,
    description: 'Department of Chemistry',
  },
  {
    name: 'Computer Science and Mathematics',
    code: 'CSC',
    college: College.CBAS,
    description:
      'Department of Computer Science and Mathematics — comprising programmes in Computer Science, Software Engineering, Cybersecurity, and Mathematics',
  },
  {
    name: 'Food Science and Technology',
    code: 'FST',
    college: College.CBAS,
    description: 'Department of Food Science and Technology',
  },
  {
    name: 'Geography',
    code: 'GPH',
    college: College.CBAS,
    description: 'Department of Geography',
  },
  {
    name: 'Geology',
    code: 'GLY',
    college: College.CBAS,
    description: 'Department of Geology',
  },
  {
    name: 'Geoscience',
    code: 'GEY',
    college: College.CBAS,
    description: 'Department of Geoscience',
  },
  {
    name: 'Industrial Chemistry',
    code: 'ICH',
    college: College.CBAS,
    description: 'Department of Industrial Chemistry',
  },
  {
    name: 'Information Technology',
    code: 'IFT',
    college: College.CBAS,
    description: 'Department of Information Technology',
  },
  {
    name: 'Information and Communication Technology',
    code: 'ICT',
    college: College.CBAS,
    description: 'Department of Information and Communication Technology',
  },
  {
    name: 'Physics',
    code: 'PHY',
    college: College.CBAS,
    description: 'Department of Physics',
  },
  {
    name: 'Statistics',
    code: 'STA',
    college: College.CBAS,
    description: 'Department of Statistics',
  },
  {
    name: 'Instrumental Science',
    code: 'INS',
    college: College.CBAS,
    description: 'Department of Instrumental Science',
  },
];
