import { Level, Semester } from '../../../generated/prisma';

export const UNIVERSITY_COURSES_SEED = [
    { code: 'GST101', name: 'Communication in English I', level: Level.LEVEL_100, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST103', name: 'Nigerian Peoples and Culture', level: Level.LEVEL_100, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST105', name: 'Introduction to Philosophy and Logic', level: Level.LEVEL_100, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST111', name: 'Communication in English II', level: Level.LEVEL_100, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST117', name: 'Use of Library, ICT and Study Skills', level: Level.LEVEL_100, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST201', name: 'Peace Studies and Conflict Resolution', level: Level.LEVEL_200, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST203', name: 'Entrepreneurship I', level: Level.LEVEL_200, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST205', name: 'Introduction to Entrepreneurship', level: Level.LEVEL_200, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST211', name: 'Entrepreneurship in Practice', level: Level.LEVEL_200, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST301', name: 'Venture Creation', level: Level.LEVEL_300, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST311', name: 'Entrepreneurship II', level: Level.LEVEL_300, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST401', name: 'Entrepreneurship III', level: Level.LEVEL_400, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'GST501', name: 'Entrepreneurship IV', level: Level.LEVEL_500, credits: 2, semester: Semester.FIRST, departmentCode: 'GST', isGeneral: true, isLocked: true },
    { code: 'PIF101', name: 'Christian Faith and Life I', level: Level.LEVEL_100, credits: 2, semester: Semester.FIRST, departmentCode: 'PIF', isGeneral: true, isLocked: true },
    { code: 'PIF201', name: 'Christian Faith and Life II', level: Level.LEVEL_200, credits: 2, semester: Semester.FIRST, departmentCode: 'PIF', isGeneral: true, isLocked: true },
    { code: 'PIF301', name: 'Christian Faith and Life III', level: Level.LEVEL_300, credits: 2, semester: Semester.FIRST, departmentCode: 'PIF', isGeneral: true, isLocked: true },
    { code: 'PIF401', name: 'Christian Faith and Life IV', level: Level.LEVEL_400, credits: 2, semester: Semester.FIRST, departmentCode: 'PIF', isGeneral: true, isLocked: true },
    { code: 'PIF501', name: 'Christian Faith and Life V', level: Level.LEVEL_500, credits: 2, semester: Semester.FIRST, departmentCode: 'PIF', isGeneral: true, isLocked: true },
    { code: 'SDN101', name: 'Introduction to Sustainable Development', level: Level.LEVEL_100, credits: 2, semester: Semester.FIRST, departmentCode: 'SDN', isGeneral: true, isLocked: true },
    { code: 'SDN201', name: 'Sustainable Development II', level: Level.LEVEL_200, credits: 2, semester: Semester.FIRST, departmentCode: 'SDN', isGeneral: true, isLocked: true },
    { code: 'SDN301', name: 'Sustainable Development III', level: Level.LEVEL_300, credits: 2, semester: Semester.FIRST, departmentCode: 'SDN', isGeneral: true, isLocked: true },
    { code: 'SDN401', name: 'Sustainable Development IV', level: Level.LEVEL_400, credits: 2, semester: Semester.FIRST, departmentCode: 'SDN', isGeneral: true, isLocked: true },
    { code: 'SDN501', name: 'Sustainable Development V', level: Level.LEVEL_500, credits: 2, semester: Semester.FIRST, departmentCode: 'SDN', isGeneral: true, isLocked: true },
    { code: 'ENT211', name: 'Entrepreneurship in Practice I', level: Level.LEVEL_200, credits: 2, semester: Semester.FIRST, departmentCode: 'ENT', isGeneral: true, isLocked: true },
    { code: 'ENT311', name: 'Venture Creation I', level: Level.LEVEL_300, credits: 2, semester: Semester.FIRST, departmentCode: 'ENT', isGeneral: true, isLocked: true },
    { code: 'ESM101', name: 'Earth Sciences I', level: Level.LEVEL_100, credits: 2, semester: Semester.FIRST, departmentCode: 'ESM', isGeneral: true, isLocked: true },
    { code: 'ESM201', name: 'Earth Sciences II', level: Level.LEVEL_200, credits: 2, semester: Semester.FIRST, departmentCode: 'ESM', isGeneral: true, isLocked: true },
    { code: 'ESM301', name: 'Earth Sciences III', level: Level.LEVEL_300, credits: 2, semester: Semester.FIRST, departmentCode: 'ESM', isGeneral: true, isLocked: true },
    { code: 'ESM401', name: 'Earth Sciences IV', level: Level.LEVEL_400, credits: 2, semester: Semester.FIRST, departmentCode: 'ESM', isGeneral: true, isLocked: true },
    { code: 'ESM501', name: 'Earth Sciences V', level: Level.LEVEL_500, credits: 2, semester: Semester.FIRST, departmentCode: 'ESM', isGeneral: true, isLocked: true },
];
