/*
  Warnings:

  - You are about to drop the column `venue` on the `schedules` table. All the data in the column will be lost.
  - A unique constraint covering the columns `[courseCode,sessionId]` on the table `schedules` will be added. If there are existing duplicate values, this will fail.

*/
-- AlterTable
ALTER TABLE "schedules" DROP COLUMN "venue",
ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "isManualOverride" BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE UNIQUE INDEX "schedules_courseCode_sessionId_key" ON "schedules"("courseCode", "sessionId");
